// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfBnUcCC-zX--TIFZeIcgwZ3FQ79dHPkQ',
    appId: '1:39180788779:web:49d3c8273c1473e912f66e',
    messagingSenderId: '39180788779',
    projectId: 'fi-chel-pjt',
    authDomain: 'fi-chel-pjt.firebaseapp.com',
    databaseURL: 'https://fi-chel-pjt-default-rtdb.firebaseio.com',
    storageBucket: 'fi-chel-pjt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_T0DWUicyw5I13LIj_oE0rh5TLmYld8',
    appId: '1:39180788779:android:21b5173d3bca842a12f66e',
    messagingSenderId: '39180788779',
    projectId: 'fi-chel-pjt',
    databaseURL: 'https://fi-chel-pjt-default-rtdb.firebaseio.com',
    storageBucket: 'fi-chel-pjt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwryn427uKZSmNrvpYeWVIViastU83A6g',
    appId: '1:39180788779:ios:576c4c9852948e8d12f66e',
    messagingSenderId: '39180788779',
    projectId: 'fi-chel-pjt',
    databaseURL: 'https://fi-chel-pjt-default-rtdb.firebaseio.com',
    storageBucket: 'fi-chel-pjt.appspot.com',
    iosBundleId: 'com.example.myFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwryn427uKZSmNrvpYeWVIViastU83A6g',
    appId: '1:39180788779:ios:576c4c9852948e8d12f66e',
    messagingSenderId: '39180788779',
    projectId: 'fi-chel-pjt',
    databaseURL: 'https://fi-chel-pjt-default-rtdb.firebaseio.com',
    storageBucket: 'fi-chel-pjt.appspot.com',
    iosBundleId: 'com.example.myFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfBnUcCC-zX--TIFZeIcgwZ3FQ79dHPkQ',
    appId: '1:39180788779:web:4ec29a355c6c805512f66e',
    messagingSenderId: '39180788779',
    projectId: 'fi-chel-pjt',
    authDomain: 'fi-chel-pjt.firebaseapp.com',
    databaseURL: 'https://fi-chel-pjt-default-rtdb.firebaseio.com',
    storageBucket: 'fi-chel-pjt.appspot.com',
  );

}