// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWfey3D_CsrFa10G8ZkhqwKPFJTYRvxs',
    appId: '1:387303738184:web:07b418312ff151859e817d',
    messagingSenderId: '387303738184',
    projectId: 'hsmcoi-chellenge-project',
    authDomain: 'hsmcoi-chellenge-project.firebaseapp.com',
    storageBucket: 'hsmcoi-chellenge-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjaVDr6Ut3NbM-IS6p703w97s4YezYH8',
    appId: '1:387303738184:android:5a54fafe9f6f9ef29e817d',
    messagingSenderId: '387303738184',
    projectId: 'hsmcoi-chellenge-project',
    storageBucket: 'hsmcoi-chellenge-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGO5sFg7T2JyYpsWJ12EsOPPygRxUN-js',
    appId: '1:387303738184:ios:d3b3d0031002b8689e817d',
    messagingSenderId: '387303738184',
    projectId: 'hsmcoi-chellenge-project',
    storageBucket: 'hsmcoi-chellenge-project.appspot.com',
    iosBundleId: 'com.example.myFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGO5sFg7T2JyYpsWJ12EsOPPygRxUN-js',
    appId: '1:387303738184:ios:d3b3d0031002b8689e817d',
    messagingSenderId: '387303738184',
    projectId: 'hsmcoi-chellenge-project',
    storageBucket: 'hsmcoi-chellenge-project.appspot.com',
    iosBundleId: 'com.example.myFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABWfey3D_CsrFa10G8ZkhqwKPFJTYRvxs',
    appId: '1:387303738184:web:9d4e7dbdeab20def9e817d',
    messagingSenderId: '387303738184',
    projectId: 'hsmcoi-chellenge-project',
    authDomain: 'hsmcoi-chellenge-project.firebaseapp.com',
    storageBucket: 'hsmcoi-chellenge-project.appspot.com',
  );
}
